steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, -t, '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA', .]
  - name: gcr.io/cloud-builders/docker
    args: [push, '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA']
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA'
substitutions:
  _REGION: southamerica-west1
  _REPOSITORY: gmail-downloader
  _IMAGE: gmail-cloud-run
options:
  logging: CLOUD_LOGGING_ONLY
